import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages  extends Translations{

  @override
  Map<String,Map<String,String>> get keys =>{
    'en_US':{
      'message':'GOOGLY 11',
      'MY_INFO_setting':'My Info & Settings',
      'App_language':'App Language',
      'English':'(English)>',
      'Name':'Name',
      'Gender':'Gender',
      'PER FRIEND':'PER FRIEND',
      'Male':'Male',
      'Save Team':'Save Team',
      'Female':'Female',
      'Others':'Others',
      'LOGOUT':'LOGOUT',
      'STRATEGIC TIMEOUT':'STRATEGIC TIMEOUT',
      'Invite Friends & Earn':'Invite Friends & Earn',
      'UPDATE PROFILE':'UPDATE PROFILE',
      'Are logout':'Are you sure you want to logout',
      'NO':'NO',
      'YES':'YES',
      'Preview':'Preview',
      'Skill':'Skill:',
      'Select Substitutes':'Select Substitutes',
      'My balance':'My balance',
      'Fantasy Point':'Fantasy Point System',
      'Terms':'Terms And Conditions',
      'Transactions':'My Transactions',
      'ReferEarn':'Refer & Earn',
      'Howtoplay':'How to play',
      'Services and leadership':'Services and leadership',
      'Watch LIVE':'Watch LIVE',
      'About Us':'About Us',
      'Contact Us':'Contact Us',
      'UPCOMING':'UPCOMING',
      'LIVE':'LIVE',
      'COMPLETED':'COMPLETED',
      'Contest':'Contest',
      'Especially':'Especially For You',
      'Select Captain and Vice-captain':'Select Captain and Vice-captain',
      'CONTINUE':'CONTINUE',
      'Winnigs':'Winnigs',
      'Withdraw':'Withdraw',
      'Captain':'Captain',
      'Vice Captain':'Vice Captain',
      'Preparing':'Preparing',
      'Line-up is public information':'Line-up is public information Although we \ndisplay it from the best sources possible, we \nsuggest you verify your sources as well',
      'Rank':'Rank',
      'Next':'Next',
      'Earn':'Earn',
      'The New Point System':'The New Point System will come into effect for \n'
          'matches that go live from 4th \n march,2023 onwards',
      'My Wallet':'My Wallet',
      'Leaderboards':'Leaderboards',
      'Invite via Whatsapp':'Invite via Whatsapp',
      'How it works':'How it works',
      'Total Balance':'Total Balance',
      'Max Seven':'Max Seven Player from the team',
      'View Transaction':'View Transaction',
      'Add Cash':'Add',
      'Create Team':'Create Team',
      'Points':'Points',
      'Fantasy Point System':'Fantasy Point System on Googly11',
      'Bonus Points':'Bonus Points',
      'Points to Remember':'Points to Remember:',
      'Use Bonus Points to avail':'Use Bonus points to avail flat 10% discount on all contests',
      'Winning Balance':'Winning Balance',
      '1 for every':'1 for every Rs10 spend on a contest entry',
      'Be the contest':'Be the first in your network to join the contest 0',
      'Are you just getting started':'Are you just getting started with Fantasy games? \n'
      "Whether it is fantasy cricket, having an \n"
          "understanding about the points system is \n"
          "the best way to select matches and get started with it. \n"
          "The total points calculated for each match will be \n"
          "based on the grid below. So, pick your game, select",
    },
    'hindi_IND':{
      'message':'गूगली 11',
      'MY_INFO_setting': 'मेरी जानकारी सेटिंग',
      'App_language':'ऐप भाषा',
      'English':'(अंग्रेज़ी)>',
      'Name':'नाम',
      'Gender':'लिंग',
      'Male':'पुरूष',
      'Female':'महिला',
      'PER FRIEND':'प्रति मित्र',
      'Invite via Whatsapp':'व्हाट्सएप के माध्यम से आमंत्रित करें',
      'Others':'अन्य',
      'LOGOUT':'लॉग आउट',
      'STRATEGIC TIMEOUT':'रणनीतिक समयसीमा',
      'UPDATE PROFILE':'प्रोफ़ाइल अपडेट करें',
      'Are logout':'क्या आप लॉग आउट करना चाहते हैं',
      'NO':'नहीं',
      'YES':'हाँ',
      'Skill':'कौशल:',
      'Save Team':'टीम बचाओ',
      'How it works':'यह कैसे काम करता है',
      'My balance':'मेरा संतुलन',
      'Fantasy Point':'काल्पनिक बिंदु प्रणाली',
      'Terms':'नियम और शर्तें',
      'Invite Friends & Earn':'दोस्तों को आमंत्रित करें और कमाएँ',
      'Transactions':'लेन-देन देखें',
      'ReferEarn':'देखें और कमाएँ',
      'Howtoplay':'कैसे खेलें',
      'Services and leadership':'सेवाएँ और नेतृत्व',
      'Watch LIVE':'लाइव देखें',
      'About Us':'हमारे बारे में',
      'Contact Us':'संपर्क करें',
      'Preview':'पूर्वावलोकन',
      'Captain':'कप्तान',
      'Select Substitutes':'विकल्प चुनें',
      'Vice Captain':'उप कप्तान',
      'UPCOMING':'आगामी',
      'Max Seven':'टीम से अधिकतम सात खिलाड़ी',
      'LIVE':'रहना',
      'Select Captain and Vice-captain':'कप्तान और उप-कप्तान चुनें',
      'COMPLETED':'पूर्ण',
      'Contest':'प्रतियोगिता',
      'Especially':'विशेष रूप से आप के लिए',
      'CONTINUE':'जारी रखना',
      'Winnigs':'विनिग्स',
      'Rank':'रैंक',
      'Preparing':'तैयारी',
      'Next':'अगला',
      'Earn':'कमाना',
      'Leaderboards':'लीडरबोर्ड',
      'My Wallet':'मेरा बटुआ',
      'Total Balance':'कुल शेष',
      'View Transaction':'लेनदेन देखें',
      'Add Cash':'जोड़ें',
      'Withdraw':'वापस लेना',
      'Bonus Points':'बोनस अंक',
      'Create Team':'टीम बनाएँ',
      'Points':'अंक',
      'Fantasy Point System':'गुगली11 पर फैंटेसी प्वाइंट सिस्टम',
      'Use Bonus Points to avail':'सभी प्रतियोगिताओं पर फ्लैट 10% छूट का लाभ उठाने के लिए बोनस अंक का उपयोग करें',
      'Winning Balance':'जीत का संतुलन',
      '1 for every':'प्रतियोगिता में प्रवेश पर प्रत्येक 10 रुपये खर्च करने पर 1',
      'Be the contest':'प्रतियोगिता 0 में शामिल होने वाले अपने नेटवर्क के पहले व्यक्ति बनें',
      'Are you just getting started':'क्या आप अभी फ़ैंटेसी गेम्स से शुरुआत कर रहे हैं? \n'
          "चाहे वह फ़ैंटेसी क्रिकेट हो, \n का होना"
          "अंक प्रणाली के बारे में समझ \n है"
          "मैचों का चयन करने और उसके साथ शुरुआत करने का सबसे अच्छा तरीका। \n"
          "प्रत्येक मैच के लिए गणना किए गए कुल अंक \n होंगे"
          "नीचे ग्रिड के आधार पर। तो, अपना गेम चुनें, चुनें",
      'Points to Remember':'याद रखने लायक बातें:',
      'The New Point System':'नया प्वाइंट सिस्टम लागू होगा \n'
      'मैच जो 4 मार्च, 2023 से लाइव होंगे',

      'Line-up is public information':'लाइन-अप सार्वजनिक जानकारी है, हालांकि हम\n इसे सर्वोत्तम संभव स्रोतों से प्रदर्शित करते हैं, हमारा सुझाव \n है कि आप अपने स्रोतों को भी सत्यापित करें',
    }
  };
}