import 'NewDataClass.dart';

class Autogenerated {
  int? status;
  List<NewDataClass>? data;
  int? total;

  Autogenerated({this.status, this.data, this.total});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      status: json['status'],
      data: (json['data'] as List).map((item) => NewDataClass.fromJson(item)).toList(),
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['total'] = this.total;
    return data;
  }
}